### PR TITLE
added fmt and clippy for Github actions

### LINKED ISSUE #3: Add clippy and fmt to the CI
As in the title.

### PR DESCRIPTION
**Pull request by tarunsamanta2k20**
Add clippy and fmt to the CI #3 

closes #3

### CODE REVIEW

**Comment by podusowski** [comment]
Why does it need write perms?

**Comment by tarunsamanta2k20** [comment]
> Why does it need write perms?

Soory. Maybe only read. You may try by enabling read only permission. It is required for reading secret.

**Comment by podusowski** [comment]
That's odd. Current build and tests work just fine on default settings. Can it be done somehow similar?

**Comment by tarunsamanta2k20** [comment]
> That's odd. Current build and tests work just fine on default settings. Can it be done somehow similar?

I can write simple commend as well but that will not show proper logs if anything fails if don't use marketplace action.

**Comment by podusowski** [comment]
Yeah, I think simpler is better in this case. https://github.com/mbrobbel/rustfmt-check says it commits files after formatting and I don't really like that idea. Thanks. :)

**Comment by tarunsamanta2k20** [comment]
> Yeah, I think simpler is better in this case. https://github.com/mbrobbel/rustfmt-check says it commits files after formatting and I don't really like that idea. Thanks. :)

I am taking about clippy check.

**Comment by podusowski** [comment]
Oh, all right. Although it seems it doesn't work that well anyway. 
 
image

**Comment by tarunsamanta2k20** [comment]
@podusowski you may run it now. I believe, It'll work.

**Comment by tarunsamanta2k20** [comment]
you have to merge it then it won't give resources that are not accessible due to integration error.

**Comment by tarunsamanta2k20** [comment]
Fmt check will fail I think have an issue in lib.rs

**Comment by podusowski** [comment]
Thanks!

**Pull request merged**
